### ISSUE TITLE
Limit any_login to specific user

### ISSUE THREAD

**Issue by damienlethiec** [igorkasyanchuk/any_login#39]
Hi there,

I want to limit any_login access to a specific user. I used the following code and it works:

```
  config.verify_access_proc = proc do |controller|
    controller.current_user&.email == "myemail@email.com"
  end
```

Unfortunately, when I change my user thanks to any login, as I am logged in as another user, I cannot come back anymore. In the view I could do something like `current_user&.email == "myemail@email.com" || any_login_previous_ids.present?` but not in the initializer.

Do you have any tips to be able to use any_login based on the "initial user" ?

Thanks so much,
Damien

**Comment by damienlethiec** [comment]
Hi,

Sorry to come back to you but the issue does not seems to be solved.

Thanks so much !

**Comment by igorkasyanchuk** [comment]
Hi @damienlethiec 

I don't have a quick solution to this issue. Because I don't store the original user.

Maybe you can do something with it, maybe it's would be possible to write ID of the user to the session and check if verify_access_proc.

Something like create a hook after user is logged in and set in the session original ID. But what if user is switching from A => B => C => Z user ? how to remember that "A" was the really original user?

**Comment by damienlethiec** [comment]
Yep, this is exactly my issue. I will think about it but it could maybe be interesting to store the original user in the gem ?

Thanks so much

**Comment by igorkasyanchuk** [comment]
I don't know what is the "original" user.

what if in app you were logged as B originally. But only "A" is the super-user. Then you need to tell gem that when you switch to "A" he is the super user and remember him. And then A => B => C => Z ... 

Probably you need to look at the gem "pretender", they have only one switch from A => B and then only back to A.

Any_login is very useful in development and testing.

**Comment by damienlethiec** [comment]
Ok got it. It would be super useful to remember the really first user you logged in with, before the first switch (B in your case) but I got you point. I will check the pretender gem ;)
